# Generated by Django 5.0.1 on 2024-01-12 22:25

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0003_giftidea"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="IdeaList",
            new_name="IdeaCollection",
        ),
    ]
