# Generated by Django 5.0.1 on 2024-01-13 17:49

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0004_rename_idealist_ideacollection"),
    ]

    operations = [
        migrations.AlterField(
            model_name="ideacollection",
            name="owner",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="idea_collections",
                related_query_name="idea_collection",
                to=settings.AUTH_USER_MODEL,
                verbose_name="owner",
            ),
        ),
    ]
