# Generated by Django 5.0.1 on 2024-01-13 20:48

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0005_alter_ideacollection_owner"),
    ]

    operations = [
        migrations.AddField(
            model_name="giftidea",
            name="name",
            field=models.CharField(
                default="Gift Idea", max_length=100, verbose_name="name"
            ),
            preserve_default=False,
        ),
    ]
