# Generated by Django 5.0.1 on 2024-01-13 21:08

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0006_giftidea_name"),
    ]

    operations = [
        migrations.AddField(
            model_name="giftidea",
            name="mention_count",
            field=models.PositiveSmallIntegerField(
                default=1,
                help_text="The number of times this gift ideas has been brought up.",
                verbose_name="mention count",
            ),
        ),
    ]
