# Generated by Django 5.0.1 on 2024-01-14 01:26

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0007_giftidea_mention_count"),
    ]

    operations = [
        migrations.AlterField(
            model_name="giftidea",
            name="mention_count",
            field=models.PositiveSmallIntegerField(
                default=1,
                help_text="The number of times this gift idea has been brought up.",
                verbose_name="mention count",
            ),
        ),
    ]
